### ISSUE TITLE
Proposal: use official data and map 

### ISSUE THREAD

**Issue by davidoesch** [zdavatz/covid2019_ch_map#5]
This is a proposal

1) download *official* data https://github.com/openZH/covid_19 
2) use the attached KML:  set the kanton polygon to the corresponding color value 
[kantone_50m.zip](https://github.com/zdavatz/covid2019_ch_map/files/4358295/kantone_50m.zip)
3) upload the KML to a webspace , keep the URL to the file stable
4) import it to the *official* browser http://map.geo.admin.ch/?layers=KML||http://mydomain.com/file.kml
5) embed share map etc according to https://help.geo.admin.ch/#/?ids=52&lang=en

-everytime you update the kml, map is updated
- combine info with +800 available layers

**Comment by zdavatz** [comment]
Tanks @davidoesch Can you send me a pull request for this please?

**Comment by zdavatz** [comment]
The data [here](https://github.com/openZH/covid_19) is a mess. Each Canton has a different format.

**Comment by davidoesch** [comment]
they are on the way to consolidate the format.... during these days.

**Comment by davidoesch** [comment]
> Thanks @davidoesch Can you send me a pull request for this please?

would involve  some heavy coding behind my current script kidding capabilities

**Comment by davidoesch** [comment]
> The data [here](https://github.com/openZH/covid_19) is a mess. Each Canton has a different format.

here a cleaned version https://github.com/openZH/covid_19/blob/master/COVID19_Cases_Cantons_CH_total.csv

**Comment by zdavatz** [comment]
ZH last update is 2020-03-14. To old.

**Comment by zdavatz** [comment]
See also this issue: https://github.com/openZH/covid_19/issues/22

**Comment by zdavatz** [comment]
@davidoesch kannst hier die Daten für heute abfüllen und mir einen PR senden bitte?  https://github.com/zdavatz/covid19_ch/blob/master/data-cantons-csv/dd-covid19-ch-cantons-latest.csv

und auch hier brauchen wir die Daten für heute.

https://github.com/zdavatz/covid19_ch/blob/master/data-switzerland-csv/dd-covid19-ch-switzerland-latest.csv

**Comment by zdavatz** [comment]
@davidoesch your KML file is great, thank you!
